[tox]
envlist = py310,py311,py312,py313,py314
isolated_build = True
skip_missing_interpreters = True

[testenv]
deps = pytest
commands = pytest {posargs}

[testenv:mypy]
description = Static type check
basepython = python3.10
deps =
    mypy
    types-requests
commands = mypy {posargs}
